# Generated by Django 4.2.28 on 2026-03-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_event_image_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsuggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_suggestions/'),
        ),
    ]
